---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devspaces-config-job-runner
  namespace: openshift-gitops
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devspaces-config-job-runner
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters
  verbs:
  - get
  - list
  - watch
  - patch
  - update

